spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: debug